import type { Metadata } from "next";
import type { ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BarChart3, Check, FileSearch, Gauge, Globe2, Link2, MapPin, SearchCheck, Settings2, Target } from "lucide-react";
import { getServiceBySlug, services, type ServiceDetail } from "@/lib/services";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return services.map((service) => ({ slug: service.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const service = getServiceBySlug((await params).slug);
  if (!service) return { title: "Service Not Found | Diginfo" };
  if (service.slug === "social-media-marketing") {
    return {
      title: "Social Media Marketing Agency - Instagram & Facebook | Diginfo",
      description: "Diginfo is a social media marketing agency running Instagram, Facebook and reels-first campaigns built for engagement and leads. Free social audit inside.",
      alternates: { canonical: "/services/social-media-marketing" },
      openGraph: { title: "Social Media Marketing Agency - Instagram & Facebook | Diginfo", description: "Instagram, Facebook and reels-first campaigns built for engagement and leads.", type: "website", url: "/services/social-media-marketing" },
    };
  }
  return {
    title: service.seoTitle,
    description: service.seoDescription,
    alternates: { canonical: `/services/${service.slug}` },
    openGraph: { title: service.seoTitle, description: service.seoDescription, type: "website", url: `/services/${service.slug}` },
  };
}

export default async function ServiceDetailPage({ params }: Props) {
  const service = getServiceBySlug((await params).slug);
  if (!service) notFound();
  const relatedServices = services.filter((item) => item.slug !== service.slug).slice(0, 3);
  if (service.slug === "search-engine-optimization") return <SeoServiceDetailPage relatedServices={relatedServices} />;
  if (service.slug === "ai-search-optimisation-aeo-geo") return <AiSearchServiceDetailPage relatedServices={relatedServices} />;
  if (service.slug === "performance-marketing") return <PerformanceMarketingDetailPage relatedServices={relatedServices} />;
  if (service.slug === "social-media-marketing") return <SocialMediaMarketingDetailPage relatedServices={relatedServices} />;

  return <GenericServiceDetailPage service={service} relatedServices={relatedServices} />;
}

const socialMediaFaqs = [
  ["Do I actually need social media marketing for my business?", "If your customers spend time on Instagram or Facebook, social media helps them discover you, trust you, and remember you before they buy. It matters most for visual businesses and reputation-led local services."],
  ["How fast will I see results from social media marketing?", "Most accounts see engagement improve within three to four weeks of consistent posting. Meaningful follower growth and reach usually follow by six to eight weeks, with reels-heavy accounts often moving faster."],
  ["How much does social media management cost in India?", "Pricing depends on the platforms, posting frequency, creative production, and whether paid ads are included. Diginfo scopes pricing after understanding your goals, then gives you a real estimate."],
  ["What does an Instagram marketing agency actually do for a small business?", "It plans a content calendar, produces or edits reels and posts, manages your schedule, and responds to comments and messages. The goal is to turn consistent, on-brand content into enquiries and customers, not just likes."],
  ["How do I find a good social media marketing agency near me?", "Ask to see real client work, check whether content is produced in-house, and look for reporting on engagement and leads instead of follower counts alone. Relevant local experience is a strong signal."],
  ["Is social media marketing worth it for a startup with a small budget?", "Yes. It is one of the most cost-effective ways to build early credibility and an audience. A small, reliable posting schedule usually outperforms a large burst of content that stops after a month."],
  ["Do restaurants really need reels, or is regular posting enough?", "Reels consistently outperform static posts for food and hospitality because dishes, ambience, and behind-the-scenes moments are naturally engaging on video. A few strong reels a week will usually outperform daily static posts alone."],
  ["What's the difference between Instagram marketing and Facebook marketing?", "Instagram is strongest for visual discovery through reels, stories, and carousels. Facebook is stronger for community building, local pages, groups, reviews, and an older or more local audience. Most brands need a different approach for each."],
  ["How is Diginfo different from other social media marketing agencies?", "Diginfo produces content in-house, assigns one named consultant to each account, and reports on reach, engagement, and leads rather than just likes or follower counts. There are no lock-in contracts."],
] as const;

function SocialMediaMarketingDetailPage({ relatedServices }: { relatedServices: ServiceDetail[] }) {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: socialMediaFaqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
  const organizationSchema = { "@context": "https://schema.org", "@type": "Organization", name: "Diginfo", url: "https://diginfo.ai", logo: "https://diginfo.ai/logo.png", sameAs: ["https://www.facebook.com/diginfoexpert/", "https://www.instagram.com/diginfo_official/", "https://www.linkedin.com/company/diginfo-ai/"] };
  const services = [
    ["Instagram marketing", "Reels, carousels, stories, and profile optimisation built around growth and engagement."],
    ["Facebook marketing", "Page management, community building, and content for your existing local or national audience."],
    ["Content creation", "Photography, videography, and graphic design produced in-house for every post."],
    ["Reels & short-form video", "Scripted, shot, and edited for the formats each platform currently favours."],
    ["Paid social promotion", "Boosted posts and targeted campaigns layered on top of organic content for faster reach."],
    ["Community management", "Comments, messages, and reviews monitored and answered in your brand voice."],
  ] as const;
  const industries = [
    ["Restaurants", "Visual-first content around dishes, ambience, and reels that drive footfall and table bookings."],
    ["Real estate agents", "Property walkthroughs, reels, and local-audience targeting for a long, trust-based sales cycle."],
    ["Startups", "A lean, consistent content engine that establishes credibility quickly without a large in-house team."],
    ["Coaches & consultants", "Personal-brand content built around authority, testimonials, and audience trust."],
    ["Local & small businesses", "Hyper-local content and community engagement designed to convert nearby followers into customers."],
  ] as const;

  return <section className="services-sec service-detail-sec seo-detail-page social-media-detail-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} />
    <div className="wrap service-detail-hero">
      <Link className="card-link service-back-link" href="/services">&lt;- Back to Services</Link>
      <h1 className="services-title">The Social Media Marketing Agency That Treats Every Post Like It Has a <span className="gt">Job to Do</span></h1>
      {/* <p className="service-last-updated">Last updated: August 2026</p> */}
      <p className="services-desc">Diginfo is a social media marketing agency running Instagram marketing, Facebook marketing, and reels-first content built to grow real audiences - not just impressions. Work with a senior consultant who plans, shoots, and reports on every campaign personally.</p>
      <div className="seo-trust-strip" aria-label="Diginfo social media marketing commitments"><span><Check aria-hidden="true" />100+ brands managed across Instagram & Facebook</span><span><Check aria-hidden="true" />In-house creative team</span><span><Check aria-hidden="true" />Transparent monthly reporting</span><span><Check aria-hidden="true" />No lock-in contracts</span></div>
      <p className="smm-review">Reviewed by Jaya Panjwani, Senior Social Media Consultant at Diginfo - 7+ years running Instagram and Facebook campaigns.</p>
    </div>
    <div className="wrap seo-content">
      <section className="service-card service-detail-card seo-overview"><h2>Overview</h2><p>Social media rewards brands that show up consistently, not the ones that post occasionally and hope. Diginfo runs social media marketing around a content calendar, a creative process, and a reporting cycle - not random posts between other work. We handle strategy, shooting, editing, and community management in-house, so your voice stays consistent across every post, story, and reel.</p><blockquote className="seo-callout smm-quote">“In my 7 years running social media accounts, the biggest difference between brands that grow and brands that stall isn&apos;t budget - it&apos;s consistency. Almost every account I&apos;ve turned around started with fixing the posting schedule before touching the creative.” <strong>- Jaya Panjwani</strong></blockquote><p>This works best alongside a strong foundation elsewhere: social proof compounds when people who discover you on Instagram can also find you on <Link href="/services/search-engine-optimization">Google</Link>, in <Link href="/services/ai-search-optimisation-aeo-geo">AI search results</Link>, and through consistent <Link href="/services/performance-marketing">paid campaigns</Link>.</p></section>
      <ContentSection title="What Is Social Media Marketing?"><div className="service-card seo-mini-card"><p>Social media marketing builds your brand presence, audience, and sales pipeline across platforms like Instagram and Facebook through organic content, community management, and paid promotion. Done well, it builds long-term trust through consistent content while driving short-term leads and sales through targeted, conversion-focused posts and ads.</p></div></ContentSection>
      <ContentSection title="Which Platform Is Right for My Business?"><div className="seo-card-grid seo-card-grid-three">{[["Instagram", "Visual products, a younger audience (18-34), and fast-moving trends: lead with Instagram. Reels and Explore-page reach make it the stronger discovery engine."], ["Facebook", "For a local, community-driven, or older audience (35+), lead with Facebook. Groups, reviews, and local page discovery still drive meaningful engagement."], ["Both", "For a broad audience or when you are unsure which fits, run both with platform-specific content and cadence - not the same post copy-pasted everywhere."]].map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></ContentSection>
      <ContentSection title="Instagram vs Facebook Algorithm Behavior in 2026" intro="Platform behaviour changes. We review this guidance regularly and adapt the content calendar to what is working now."><div className="performance-results-table smm-platform-table" role="table" aria-label="Instagram and Facebook algorithm behaviour"><div className="performance-results-row performance-results-head" role="row"><span role="columnheader">What matters</span><span role="columnheader">Instagram</span><span role="columnheader">Facebook</span></div>{[["Format favoured", "Reels and Stories get the widest organic push", "Video and community or group posts perform best"], ["Distribution logic", "Reach extends beyond followers via Explore and Reels feed", "Weighted toward friends, groups, and pages people already interact with"], ["Best suited for", "Visual discovery, younger audiences, trend-driven content", "Local community building, reviews, older demographics"], ["Posting cadence", "4-5x/week, reels-heavy", "3-4x/week, community-engagement-heavy"]].map(([label, instagram, facebook]) => <div className="performance-results-row" role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell">{instagram}</span><span role="cell">{facebook}</span></div>)}</div></ContentSection>
      <ContentSection title="How We Measure Success"><div className="seo-why-list ai-benefit-list">{["Reach - unique accounts that saw your content, tracked over time, not only per post", "Engagement rate - likes, comments, shares, and saves relative to reach", "Follower quality - growth from relevant accounts, not bots or giveaway inflation", "Leads generated - DMs, comments, and clicks that become actual enquiries", "Content performance by format - the reels, carousels, and posts that drive the results"].map((item) => <div key={item}><Check aria-hidden="true" /><p>{item}</p></div>)}</div></ContentSection>
      <ContentSection title="What You Get"><div className="seo-why-list ai-benefit-list">{["A real content calendar - planned posts, reels, and stories instead of last-minute scrambling", "In-house creative production - shooting, editing, and design handled by our own team", "Reels-first strategy - short-form video prioritised for organic reach", "Community management - comments, DMs, and engagement handled daily", "Platform-specific strategy - different goals, formats, and cadence for Instagram and Facebook", "Monthly reporting - reach, engagement, follower growth, and leads reviewed with your consultant"].map((item) => <div key={item}><Check aria-hidden="true" /><p>{item}</p></div>)}</div></ContentSection>
      <ContentSection title="Our Services"><div className="seo-card-grid seo-card-grid-three">{services.map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></ContentSection>
      <ContentSection title="Built Around Your Industry"><div className="seo-card-grid seo-card-grid-three">{industries.map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><aside className="seo-callout smm-quote">“Restaurant and real estate accounts often see the fastest visible results from reels - usually within four to six weeks - because food and spaces are naturally suited to video.” <strong>- Jaya Panjwani</strong></aside></ContentSection>
      <ContentSection title="How We Work"><ol className="seo-process-list">{[["Audit & strategy", "We review your current presence, audience, and competitors before planning anything."], ["Content calendar", "A month of posts, reels, and stories planned around your goals and key dates."], ["Shoot & produce", "Our in-house team shoots and edits content, or works with what you provide."], ["Publish & engage", "Content goes live on a consistent schedule, with comments and DMs managed daily."], ["Report & refine", "A monthly review of what worked, tied to reach, engagement, and leads - not just likes."]].map(([title, body], index) => <li className="service-card" key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></ContentSection>
      <ContentSection title="Why Diginfo"><div className="seo-why-list ai-benefit-list">{["One in-house team handles strategy, creative, and community management - not outsourced freelancers.", "A named senior consultant owns your account from strategy to reporting.", "A reels-first approach built around what is working on each platform now.", "No lock-in contracts - month to month."].map((item) => <div key={item}><Check aria-hidden="true" /><p>{item}</p></div>)}</div></ContentSection>
      <ContentSection title="How We Compare"><div className="seo-comparison-wrap"><div className="seo-comparison-table" role="table" aria-label="Comparison between a typical social media agency and Diginfo"><div className="seo-comparison-row seo-comparison-head" role="row"><span role="columnheader">What matters</span><span role="columnheader">Typical agency</span><span role="columnheader">Diginfo</span></div>{[["Content production", "Outsourced or templated", "Fully in-house creative team"], ["Strategy", "Same content across platforms", "Platform-specific Instagram and Facebook strategy"], ["Reporting", "Likes and followers only", "Reach, engagement, and leads tied to goals"], ["Account handling", "Rotating managers", "One named consultant"], ["Contracts", "6-12 month lock-ins", "No lock-in"]].map(([label, agency, diginfo]) => <div className="seo-comparison-row" role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell">{agency}</span><span className="seo-comparison-diginfo" role="cell"><Check aria-hidden="true" />{diginfo}</span></div>)}</div></div></ContentSection>
      <ContentSection title="FAQs"><div className="seo-faq-list">{socialMediaFaqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></ContentSection>
      <section className="seo-audit-cta"><div><span>Free social audit</span><h2>Ready to See What Consistent Content Could Do for Your Brand?</h2><p>Get a free audit of your Instagram or Facebook presence from a senior consultant and see what is working - and what is holding your reach back.</p></div><Link className="btn btn-grad" href="/contact">Get Started</Link></section>
    </div><RelatedServices services={relatedServices.filter((item) => ["search-engine-optimization", "ai-search-optimisation-aeo-geo", "performance-marketing"].includes(item.slug))} />
  </section>;
}

const aiFaqs = [
  ["What is AI SEO?", "Optimizing your site to perform in both traditional search and AI tools like ChatGPT and Google AI Overviews - combining SEO fundamentals with entity clarity and answer-ready content."],
  ["What's the difference between AEO and GEO?", "AEO structures content to answer questions directly. GEO earns your brand a mention when generative AI tools compose an answer. Most brands need both."],
  ["Does AI SEO replace traditional SEO?", "No. AI tools pull from well-ranked, well-structured content, so AI SEO builds on strong SEO - it doesn't replace it."],
  ["How do you measure success?", "We track AI mentions and citations across ChatGPT, Gemini, and Perplexity, alongside rankings and traffic."],
  ["How long until I see results?", "Most clients see measurable AI mention activity within 60-90 days, compounding over 6-12 months - similar to standard SEO timelines."],
  ["Should I hire a separate AI SEO agency, or one that does both?", "One agency. AI SEO depends on your existing SEO foundation, so we run both as a single strategy."],
  ["How much do AI SEO services cost?", "It depends on your current site and competition. We scope every engagement after a free audit."],
] as const;

function AiSearchServiceDetailPage({ relatedServices }: { relatedServices: ServiceDetail[] }) {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: aiFaqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
  const organizationSchema = { "@context": "https://schema.org", "@type": "Organization", name: "Diginfo", url: "https://diginfo.ai", logo: "https://diginfo.ai/logo.png", sameAs: ["https://www.facebook.com/diginfoexpert/", "https://www.instagram.com/diginfo_official/", "https://www.linkedin.com/company/diginfo-ai/"] };
  const services = [
    ["AEO & GEO strategy", "We map the prompts your buyers ask AI tools and close the content gaps stopping you from being the answer."],
    ["AI-ready content", "Direct-answer pages, FAQs, and comparisons written to be cited by AI and rank in Google."],
    ["Schema & entity signals", "FAQ, Organization, and Product schema, plus consistent brand data across the web."],
    ["Authority & citation building", "Digital PR and mentions on high-authority sites that make AI engines trust you as a source."],
    ["AI visibility tracking", "Ongoing monitoring of how often, and how accurately, you appear across major AI tools."],
    ["AI-crawler technical SEO", "Architecture and markup audited so AI and search crawlers both read your site correctly."],
  ] as const;
  const industries = [
    ["SaaS", 'We target the "best tool for X" comparison prompts buyers put to AI assistants.'],
    ["B2B", "We get you on the shortlist AI tools generate before a call ever happens."],
    ["E-commerce", "Product-level entity data so AI shopping assistants recommend specific products, not just your homepage."],
    ["Local & service businesses", 'We pair local SEO with AEO content to win "best [service] near me" prompts.'],
    ["Startups & small teams", "We start with the highest-impact fixes first: entity clarity and a handful of strong answer pages."],
  ] as const;
  return <section className="services-sec service-detail-sec seo-detail-page ai-search-detail-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }} />
    <div className="wrap service-detail-hero"><Link className="card-link service-back-link" href="/services">&lt;- Back to Services</Link><h1 className="services-title">AI SEO Services That Get You <span className="gt">Recommended, Not Just Ranked</span></h1><p className="services-desc">Diginfo runs AI SEO services that win visibility in two places: Google&apos;s results and the AI tools your customers now ask first. We combine AI-powered SEO with dedicated AEO and GEO work, so ChatGPT, Gemini, Perplexity, and Google AI Overviews find your business, trust it, and recommend it.</p><div className="seo-trust-strip" aria-label="Diginfo AI SEO commitments"><span><Check aria-hidden="true" />100+ brands optimized for AI visibility</span><span><Check aria-hidden="true" />In-house team</span><span><Check aria-hidden="true" />Transparent monthly reporting</span><span><Check aria-hidden="true" />No lock-in contracts</span></div></div>
    <div className="wrap seo-content">
      <section className="service-card service-detail-card seo-overview"><h2>Why This Matters Now</h2><p>People still Google things. But more of them now ask an AI assistant instead and get one answer, mentioning only a few brands. Miss that mention and you don&apos;t just lose a click - you lose the sale before the customer ever sees a results page.</p><p>We treat this as one strategy, not two: strong SEO fundamentals, plus the entity clarity and structured content AI models need to cite you confidently. See our <Link href="/services/search-engine-optimization">core SEO services</Link> for the foundation this builds on.</p></section>
      <ContentSection title="AI SEO vs AEO vs GEO"><div className="seo-card-grid seo-card-grid-three">{[["AI SEO / AI-powered SEO", "The umbrella term: using AI-aware strategy to win visibility everywhere search happens, Google included."], ["AEO", "Answer Engine Optimization structures content to directly answer specific questions, so voice assistants and AI answer boxes can lift it."], ["GEO", "Generative Engine Optimization earns a mention when tools like ChatGPT or Gemini generate an answer, through entity authority and content depth, not backlinks alone."]].map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><aside className="seo-callout">We don&apos;t sell these as separate add-ons. Every engagement covers all three together, so you show up whether someone types into Google or asks an AI assistant directly.</aside></ContentSection>
      <ContentSection title="What You Get"><div className="seo-why-list ai-benefit-list">{["AI answer visibility - mentions and citations in ChatGPT, Gemini, Perplexity, and AI Overviews", "Entity clarity - consistent signals across your site and the web so AI models know who you are and why you&apos;re credible", "Answer-ready content - pages built around the exact questions and comparisons your buyers ask AI tools", "Schema and technical foundations - structured, machine-readable pages that also strengthen classic rankings", "Monthly reporting - AI citations, rankings, and traffic reviewed with your consultant"].map((item) => <div key={item}><Check aria-hidden="true" /><p>{item}</p></div>)}</div></ContentSection>
      <ContentSection title="Our Services"><div className="seo-card-grid seo-card-grid-three">{services.map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></ContentSection>
      <ContentSection title="Built Around Your Industry"><div className="seo-card-grid seo-card-grid-three">{industries.map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></ContentSection>
      <ContentSection title="How We Work"><ol className="seo-process-list">{[["Audit", "We check your current SEO, entity clarity, and whether AI tools already mention you."], ["Prompt mapping", "We research the real questions your customers ask ChatGPT, Gemini, and Perplexity."], ["Build", "We ship answer pages, schema, and authority content in sprints."], ["Track", "We monitor actual AI citations, not just keyword rank."], ["Report", "You get a plain-language monthly review with your consultant."]].map(([title, body], index) => <li className="service-card" key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></ContentSection>
      <ContentSection title="Why Diginfo"><div className="seo-why-list ai-benefit-list">{["One in-house team runs SEO, AEO, and GEO together - not as a bolt-on.", "A named senior consultant owns your account from strategy to reporting.", "We track real AI citations, not just rank checks.", "No lock-in contracts - month to month."].map((item) => <div key={item}><Check aria-hidden="true" /><p>{item}</p></div>)}</div></ContentSection>
      <ContentSection title="How We Compare"><div className="seo-comparison-wrap"><div className="seo-comparison-table" role="table" aria-label="Comparison between a typical agency and Diginfo"><div className="seo-comparison-row seo-comparison-head" role="row"><span role="columnheader">What matters</span><span role="columnheader">Typical agency</span><span role="columnheader">Diginfo</span></div>{[["AI search readiness", "Rarely addressed", "Built into every engagement"], ["AEO & GEO", "Buzzwords", "Dedicated strategy and content"], ["Tracking", "Rankings only", "Rankings plus AI citations"], ["Account handling", "Rotating managers", "One named consultant"], ["Contracts", "6-12 month lock-ins", "No lock-in"]].map(([label, agency, diginfo]) => <div className="seo-comparison-row" role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell">{agency}</span><span className="seo-comparison-diginfo" role="cell"><Check aria-hidden="true" />{diginfo}</span></div>)}</div></div></ContentSection>
      <ContentSection title="FAQs"><div className="seo-faq-list">{aiFaqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></ContentSection>
      <section className="seo-audit-cta"><div><span>Free AI search audit</span><h2>Ready to Find Out If AI Tools Already Mention You?</h2><p>Get a free AI search audit and see exactly how ChatGPT, Gemini, and AI Overviews currently describe - or ignore - your brand.</p></div><Link className="btn btn-grad" href="/contact">Get Started</Link></section>
    </div><RelatedServices services={relatedServices} />
  </section>;
}

const performanceMarketingFaqs = [
  ["What does a performance marketing agency actually do?", "Runs paid campaigns across channels like Google and Meta, with every rupee tied to a measurable outcome - leads, sales, or calls - rather than just traffic or impressions."],
  ["Google Ads vs Meta Ads - which is better?", "Neither wins outright - they solve different problems. Google Ads captures people actively searching for what you offer, so it tends to convert faster for high-intent purchases. Meta Ads reaches people before they are searching, which works better for discovery, retargeting, and visual products. Most brands need both, weighted differently by industry."],
  ["How much do performance marketing services cost in India?", "It depends on your industry, competition, and goals - ad spend and management fees are scoped separately. We review your account and market before quoting, rather than pricing blind."],
  ["How is a performance marketing agency different from a PPC company?", "PPC company usually implies a narrower focus on paid search alone. A performance marketing agency typically manages paid search, paid social, and retargeting together, with a single strategy and ROAS goal across all of them."],
  ["How long before I see results from Google Ads or Meta Ads?", "Search campaigns can show signal within 2 to 3 weeks; social and retargeting campaigns usually need 4 to 6 weeks of testing before spend should be scaled meaningfully."],
  ["Do you manage the ad spend, or just the campaigns?", "We manage strategy, setup, testing, and optimization. Ad spend is billed directly to your ad account by Google or Meta - we do not mark up media spend."],
] as const;

function PerformanceMarketingDetailPage({ relatedServices }: { relatedServices: ServiceDetail[] }) {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: performanceMarketingFaqs.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };
  const services = [
    ["Google Ads management", "Search, shopping, display, and YouTube campaigns built around high-intent commercial keywords."],
    ["Meta Ads management", "Facebook and Instagram campaigns across awareness, consideration, and conversion objectives."],
    ["PPC management", "Bid strategy, budget pacing, and account structure built for efficiency, not just spend."],
    ["Retargeting & remarketing", "Funnels that re-engage visitors who did not convert the first time."],
    ["Conversion tracking & analytics", "Pixel and tag setup so every rupee spent is measurable back to a result."],
    ["Landing page & creative testing", "The ad gets the click; the landing page gets the conversion - we test both."],
  ] as const;
  const industries = [
    ["Startups", "We prioritize the campaigns that prove product-market fit fastest, with lean budgets tested before scaling."],
    ["Real estate", "High-intent lead campaigns for buyers and renters actively searching, not broad brand-awareness spend."],
    ["E-commerce", "Google Shopping and Meta catalog ads tied directly to revenue and ROAS, not just traffic."],
    ["Local & small businesses", "Location-targeted campaigns built to bring in calls and store visits, on budgets that have to earn their keep."],
    ["B2B", "Lead-gen campaigns built for longer sales cycles, with tracking that follows a lead past the click to an actual deal."],
  ] as const;
  const comparisonRows = [
    ["Account handling", "Rotating managers", "One named consultant"],
    ["Execution", "Often outsourced", "Fully in-house team"],
    ["Reporting", "Spend and clicks only", "ROAS and conversions tied to revenue"],
    ["Testing", "Launch and hope", "Controlled tests before scaling budget"],
    ["Contracts", "6-12 month lock-ins", "No lock-in"],
  ] as const;

  return <section className="services-sec service-detail-sec seo-detail-page performance-marketing-detail-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <div className="wrap service-detail-hero"><Link className="card-link service-back-link" href="/services">&lt;- Back to Services</Link><h1 className="services-title">The Performance Marketing Agency That Shows You the Math Behind <span className="gt">Every Rupee Spent</span></h1><p className="services-desc">Diginfo is a performance marketing agency running paid campaigns across Google Ads, Meta Ads, and retargeting funnels - built around leads, sales, and calls, not clicks. Work directly with a senior consultant who owns your account and your ad spend like it&apos;s their own.</p><div className="seo-trust-strip" aria-label="Diginfo performance marketing commitments"><span><Check aria-hidden="true" />100+ campaigns managed</span><span><Check aria-hidden="true" />In-house team</span><span><Check aria-hidden="true" />Transparent monthly reporting</span><span><Check aria-hidden="true" />No lock-in contracts</span></div></div>
    <div className="wrap seo-content">
      <section className="service-card service-detail-card seo-overview"><h2>Overview</h2><p>Paid ads spend money the moment you turn them on - so every rupee needs a reason. Diginfo builds performance marketing campaigns around one measure: return on ad spend, not impressions or vanity reach. We plan around your actual conversion goals, test audiences and creatives before scaling budget, and report on what the spend actually produced.</p><p>This works best paired with strong organic foundations - paid traffic converts higher when your <Link href="/services/search-engine-optimization">SEO</Link> and <Link href="/services/ai-search-optimisation-aeo-geo">AI search presence</Link> are already solid, since buyers research a brand across channels before they click an ad.</p></section>
      <ContentSection title="Performance Marketing Agency vs Companies vs Services"><div className="seo-card-grid seo-card-grid-three">{[["Performance marketing companies", "Businesses that run paid acquisition as a core offering, usually across Google, Meta, and retargeting under one roof."], ["Performance marketing services", "The individual deliverables inside that offering: campaign setup, conversion tracking, creative testing, and optimization."], ["Performance marketing agency", "An ongoing, managed relationship: strategy, execution, and reporting handled monthly, with a team accountable for your ROAS over time."]].map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><aside className="seo-callout"><strong>Where Diginfo fits:</strong> we run as a full-service performance marketing agency, but every client gets a named consultant who personally owns the account - not a rotating team learning on your budget.</aside></ContentSection>
      <ContentSection title="What You Get"><div className="seo-why-list ai-benefit-list">{["Campaigns built around real conversions - leads, purchases, calls, or enquiries, not just clicks", "Tighter budget control - testing and conversion tracking before we scale spend", "Retargeting funnels - bring warm audiences back instead of paying to re-acquire them", "Transparent reporting - spend, conversions, and ROAS reviewed with your consultant every month", "Channel-specific expertise - Google Ads and Meta Ads run by specialists in each platform, not one generalist managing both"].map((item) => <div key={item}><Check aria-hidden="true" /><p>{item}</p></div>)}</div></ContentSection>
      <ContentSection title="Our Services"><div className="seo-card-grid seo-card-grid-three">{services.map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></ContentSection>
      <ContentSection title="Built Around Your Industry"><div className="seo-card-grid seo-card-grid-three">{industries.map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></ContentSection>
      <ContentSection title="How We Work"><ol className="seo-process-list">{[["Define goals", "Target audiences, offers, budgets, and tracking needs, agreed upfront."], ["Set up accounts", "Ad accounts, conversion events, landing pages, and creatives built and tested."], ["Launch & test", "Google, Meta, and retargeting campaigns launched with controlled A/B tests before scaling."], ["Optimize", "Bids, budgets, audiences, and creatives adjusted based on real performance data."], ["Report", "A plain-language monthly review with your consultant, tied to ROAS, not just spend."]].map(([title, body], index) => <li className="service-card" key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></ContentSection>
      <ContentSection title="Why Diginfo"><div className="seo-why-list ai-benefit-list">{["One in-house team runs strategy, creative, and media buying - not outsourced to freelancers.", "A named senior consultant owns your account and reports to you directly.", "Campaigns judged on ROAS and conversions, not impressions or reach.", "No lock-in contracts - month to month."].map((item) => <div key={item}><Check aria-hidden="true" /><p>{item}</p></div>)}</div></ContentSection>
      <ContentSection title="Real Results"><div className="performance-results-table" role="table" aria-label="Illustrative performance marketing results"><div className="performance-results-row performance-results-head" role="row"><span role="columnheader">Metric</span><span role="columnheader">Before Diginfo</span><span role="columnheader">After 90 Days</span></div>{[["Cost per lead", "₹850", "₹410"], ["ROAS", "1.8x", "3.6x"], ["Conversion rate", "1.2%", "2.9%"]].map(([metric, before, after]) => <div className="performance-results-row" role="row" key={metric}><strong role="rowheader">{metric}</strong><span role="cell">{before}</span><span role="cell">{after}</span></div>)}</div></ContentSection>
      <ContentSection title="Client Results in Screenshots"><div className="performance-screenshots"><figure><Image src="/performance-marketing-google-ads.webp" alt="Google Ads dashboard showing clicks, cost, conversions, and cost per conversion" width={1920} height={1080} sizes="(max-width: 700px) 100vw, 50vw" /><figcaption>Google Ads Dashboard - Diginfo&apos;s own campaign for digital marketing services.</figcaption></figure><figure><Image src="/performance-marketing-meta-ads.webp" alt="Meta Ads dashboard showing campaign results, reach, frequency, and cost per result" width={1920} height={1080} sizes="(max-width: 700px) 100vw, 50vw" /><figcaption>Meta Ads Dashboard - Education industry client, 90-day performance.</figcaption></figure></div></ContentSection>
      <ContentSection title="How We Compare"><div className="seo-comparison-wrap"><div className="seo-comparison-table" role="table" aria-label="Comparison between a typical performance marketing agency and Diginfo"><div className="seo-comparison-row seo-comparison-head" role="row"><span role="columnheader">What matters</span><span role="columnheader">Typical agency</span><span role="columnheader">Diginfo</span></div>{comparisonRows.map(([label, agency, diginfo]) => <div className="seo-comparison-row" role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell">{agency}</span><span className="seo-comparison-diginfo" role="cell"><Check aria-hidden="true" />{diginfo}</span></div>)}</div></div></ContentSection>
      <ContentSection title="FAQs"><div className="seo-faq-list">{performanceMarketingFaqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></ContentSection>
      <section className="seo-audit-cta"><div><span>Free ad account audit</span><h2>Ready to See What Your Ad Spend Could Actually Return?</h2><p>Get a free audit of your current Google Ads or Meta Ads account from a senior consultant - not a sales rep.</p></div><Link className="btn btn-grad" href="/contact">Get Started</Link></section>
    </div><RelatedServices services={relatedServices.filter((service) => ["search-engine-optimization", "ai-search-optimisation-aeo-geo"].includes(service.slug))} />
  </section>;
}

function GenericServiceDetailPage({ service, relatedServices }: { service: ServiceDetail; relatedServices: ServiceDetail[] }) {
  return <section className="services-sec service-detail-sec">
    <div className="wrap service-detail-hero"><Link className="card-link service-back-link" href="/services">&lt;- Back to Services</Link><h1 className="services-title">{service.title}<br /><span className="gt">That Works.</span></h1><p className="services-desc">{service.description}</p></div>
    <div className="wrap service-detail-grid"><article className="service-detail-main"><div className="service-card service-detail-card"><h2>Overview</h2><p>{service.intro}</p></div><div className="service-card service-detail-card"><h2>What You Get</h2><ul>{service.benefits.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="service-card service-detail-card"><h2>Our Process</h2><ul>{service.process.map((item) => <li key={item}>{item}</li>)}</ul></div></article><aside className="service-detail-side"><div className="service-card service-detail-card"><h2>Core Services</h2><ul>{service.highlights.map((item) => <li key={item}>{item}</li>)}</ul><div className="tags">{service.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><Link className="btn btn-grad service-detail-cta" href="/contact">Get Started</Link></div></aside></div>
    <RelatedServices services={relatedServices} />
  </section>;
}

const benefits = [
  [Target, "Rankings for high-intent commercial keywords", "The searches buyers make right before they purchase, not just broad traffic terms."],
  [Gauge, "A technically sound website", "Improved speed, crawlability, indexing, and mobile performance."],
  [FileSearch, "Content built for search intent", "Pages that match what a searcher actually wants at each stage."],
  [Link2, "Authority and link building", "Earned backlinks and digital PR, never paid links or link farms."],
  [MapPin, "Local visibility", "For businesses that depend on nearby customers, we handle Google Business Profile, citations, and review strategy so you show up in the Map Pack."],
  [BarChart3, "Transparent monthly reporting", "Rankings, traffic, and conversions reviewed with your consultant every month."],
] as const;
const seoServices = [
  [Settings2, "Technical SEO", "Site audits, crawlability fixes, Core Web Vitals, structured data, and indexing. Audited with Semrush, Screaming Frog, and Google Search Console."],
  [SearchCheck, "On-Page SEO", "Title tags, meta descriptions, header structure, internal linking, and content optimisation across every page."],
  [FileSearch, "Content Strategy & SEO Writing", "Keyword-mapped content built around real search intent: pillar pages, supporting articles, and topic clusters that build authority over time."],
  [Link2, "Off-Page SEO & Link Building", "Earned backlinks and digital PR — never paid links or link farms that put your site at risk."],
  [MapPin, "Local SEO", "Google Business Profile optimisation, local citations, review strategy, and location-based content for businesses that rely on nearby customers."],
  [Globe2, "E-Commerce SEO", "Category and product-page optimisation, structured data for rich snippets, and marketplace visibility — including Amazon listings for sellers who need to be found on-platform. This is where we go deep: product schema, faceted-navigation handling, and the technical fixes generic providers miss on large catalogues."],
  [FileSearch, "SEO Audits & Consulting", "A standalone audit and roadmap for teams that execute in-house but want strategic direction and a second set of eyes."],
] as const;
const industries = [
  ["SaaS", "Software buyers search in stages: broad while defining the problem, then narrowing to feature and comparison searches right before booking a demo. We build content and page structures for every stage, not just top-of-funnel blog traffic that never converts."],
  ["B2B", "Longer sales cycles and multiple decision-makers mean ranking for a keyword is only step one. We optimise for the searches your buyers, influencers, and approvers each make at their stage of the decision."],
  ["Real Estate", "We pair local visibility with content for high-intent property searches — the terms buyers and renters type right before they call an agent, not generic ‘properties in [city]’ pages that rank for nothing."],
  ["E-Commerce", "Large catalogues need catalogue-grade SEO: product schema, faceted navigation, category optimisation, and marketplace visibility."],
  ["Small Businesses & Startups", "Budgets are tighter and every ranking has to earn its keep, so we prioritise the keywords that bring customers fastest rather than vanity terms that take a year to move."],
] as const;

function SeoServiceDetailPage({ relatedServices }: { relatedServices: ServiceDetail[] }) {
  return <section className="services-sec service-detail-sec seo-detail-page">
    <div className="wrap service-detail-hero"><Link className="card-link service-back-link" href="/services">&lt;- Back to Services</Link><h1 className="services-title">The SEO Company That Turns <span className="gt">Rankings Into Revenue</span></h1><p className="services-desc">A full-service SEO agency delivering organic search optimisation — technical SEO, content, and link building — for businesses across industries, from SaaS and B2B to e-commerce. Work directly with a senior SEO consultant from day one: no account managers relaying messages, no junior teams learning on your budget.</p><div className="seo-trust-strip" aria-label="Diginfo SEO commitments"><span><Check aria-hidden="true" />100+ brands ranked <em>Verify</em></span><span><Check aria-hidden="true" />In-house team, zero outsourcing</span><span><Check aria-hidden="true" />Transparent monthly reporting</span><span><Check aria-hidden="true" />No lock-in contracts</span></div></div>
    <div className="wrap seo-content">
      <section className="service-card service-detail-card seo-overview"><h2>Overview</h2><p>Search sends more ready-to-buy traffic than almost any other channel — but only to businesses that show up. Diginfo builds that visibility from the ground up: fixing the technical issues holding your site back, aligning every page with what your buyers actually search for, and building the authority signals that move you up the results — and keep you there.</p><p>Whether you want a full-service agency to own your entire organic strategy or a hands-on consultant to guide an in-house team, our work is judged on one measure: whether rankings turn into leads, sales, and revenue you can point to — across Google, and increasingly the AI tools your customers now ask first. For how we handle AI search specifically, see our <Link href="/services/ai-search-optimisation-aeo-geo">AI Search Optimisation service</Link>.</p></section>
      <ContentSection title="SEO Company vs Agency vs Consultant" intro="These terms get used interchangeably, but they describe different working relationships — and knowing the difference helps you hire the right fit."><div className="seo-card-grid seo-card-grid-three">{[["SEO company", "A business (like Diginfo) that offers search optimisation as a core service, usually alongside content, technical development, and reporting under one roof."], ["SEO agency", "An ongoing, managed relationship: strategy, execution, and reporting handled monthly, with a team accountable for results over time."], ["SEO consultant", "An individual expert brought in for strategy, audits, or to work alongside your existing team rather than running full execution."]].map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><aside className="seo-callout"><strong>Where Diginfo fits:</strong> we operate as a full-service SEO company and agency — but every client also gets direct access to a senior consultant who owns their account personally. You&apos;re not choosing between a company and a consultant. You get both.</aside></ContentSection>
      <ContentSection title="What You Get"><IconCards items={benefits} /></ContentSection>
      <ContentSection title="Our Organic Search Optimisation Services"><IconCards items={seoServices} ecommerceAnchor /></ContentSection>
      <ContentSection title="SEO Built Around Your Industry" intro="A SaaS company, a manufacturer, and a property developer reach completely different buyers, with different search behaviour. Here&apos;s how we adapt."><div className="seo-card-grid seo-card-grid-three">{industries.map(([title, body]) => <article className="service-card seo-mini-card" key={title}><h3>{title}</h3><p>{body} {title === "E-Commerce" && <a href="#e-commerce-seo">See the E-Commerce SEO service above.</a>}</p></article>)}</div></ContentSection>
      <ContentSection title="How We Work"><ol className="seo-process-list">{[["Audit & Discovery", "Full technical and competitive audit: site health, rankings, keyword gaps, and backlinks. No strategy is built until we know where you stand."], ["Strategy & Planning", "A prioritised roadmap tied to your revenue goals, not a generic checklist."], ["Build & Launch", "Technical fixes, on-page work, and content ship in planned sprints, so you see continuous progress."], ["Optimise & Scale", "We double down on what moves the needle and cut what doesn't."], ["Report & Grow", "Monthly reporting in plain language, reviewed live with your consultant."]].map(([title, body], index) => <li className="service-card" key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></ContentSection>
      <ContentSection title="Why Diginfo"><div className="seo-why-list">{["One team, not a vendor chain — strategy, content, technical, and reporting all in-house.", "A named consultant on every account — you always know who's working on your campaign.", "Industry-specific execution — we adapt the strategy to your buyers, whether you're a SaaS platform, a B2B firm, or an early-stage startup.", "No lock-in contracts.", "Real reporting, not vanity dashboards."].map((item) => <div key={item}><Check aria-hidden="true" /><p>{item}</p></div>)}</div></ContentSection>
      <ContentSection title="How Diginfo Compares" intro="A direct comparison of the working relationship you can expect."><div className="seo-comparison-wrap"><div className="seo-comparison-table" role="table" aria-label="Comparison between a typical SEO agency and Diginfo"><div className="seo-comparison-row seo-comparison-head" role="row"><span role="columnheader">What matters</span><span role="columnheader">Typical SEO agency</span><span role="columnheader">Diginfo</span></div>{[["Account handling", "Rotating account managers", "Named senior consultant, same person throughout"], ["Execution", "Often outsourced to freelancers", "Fully in-house team"], ["Industry approach", "One generic strategy", "Adapted per industry: SaaS, B2B, e-commerce, and more"], ["Reporting", "Rankings and traffic only", "Rankings, traffic, and conversions tied to revenue"], ["Contracts", "Often 6–12 month lock-ins", "No lock-in, month to month"], ["AI-search readiness", "Rarely addressed", "Built into every campaign, with a dedicated AEO/GEO service"]].map(([label, agency, diginfo]) => <div className="seo-comparison-row" role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell">{agency}</span><span className="seo-comparison-diginfo" role="cell"><Check aria-hidden="true" />{diginfo}</span></div>)}</div></div></ContentSection>
      <ContentSection title="Frequently Asked Questions"><div className="seo-faq-list">{[["What does an SEO company actually do?", "Improves your site’s visibility in search through technical fixes, content optimisation, and authority building — aimed at qualified organic traffic that converts, not rankings on their own."], ["How do I choose an SEO agency?", "Look for clear, revenue-tied reporting (not just rankings), direct access to the person actually working on your account, and evidence of experience in your specific industry."], ["What questions should I ask before hiring?", "How they report results, who specifically works on your account, whether they’ve worked in your industry, and what the month-to-month process looks like. Vague answers are a red flag."], ["What should I expect in the first few months?", "An audit and strategy first, not instant rankings — most legitimate SEO shows measurable movement around 90 days, building over 6–12 months as authority compounds."], ["Is SEO different for SaaS, B2B, or e-commerce?", "Yes, meaningfully. SaaS buyers research over weeks; B2B purchases involve multiple stakeholders searching at different stages; large e-commerce catalogues need catalogue-grade technical work. A generic approach misses all of this."], ["How much do organic search optimisation services cost?", "It depends on your site’s current state, competition, and goals. We scope every engagement after a free audit rather than quoting blind."]].map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></ContentSection>
      <section className="seo-audit-cta"><div><span>Free SEO audit</span><h2>Ready to see exactly where your SEO stands?</h2><p>Get a free, no-obligation audit from a senior SEO consultant — not a sales rep.</p></div><Link className="btn btn-grad" href="/contact">Get Started</Link></section>
    </div><RelatedServices services={relatedServices} />
  </section>;
}

function ContentSection({ title, intro, children }: { title: string; intro?: string; children: ReactNode }) { return <section className="seo-section"><div className="seo-section-head"><h2>{title}</h2>{intro && <p>{intro}</p>}</div>{children}</section>; }
function IconCards({ items, ecommerceAnchor = false }: { items: readonly (readonly [typeof Target, string, string])[]; ecommerceAnchor?: boolean }) { return <div className="seo-card-grid seo-card-grid-three">{items.map(([Icon, title, body]) => <article className="service-card seo-icon-card" id={ecommerceAnchor && title === "E-Commerce SEO" ? "e-commerce-seo" : undefined} key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{body}</p></article>)}</div>; }
function RelatedServices({ services: relatedServices }: { services: ServiceDetail[] }) { return <div className="wrap service-related"><h2>Explore More Services</h2><div className="services-grid service-related-grid">{relatedServices.map((item) => <div className="service-card" key={item.slug}><h3>{item.title}</h3><p>{item.description}</p><Link className="card-link" href={`/services/${item.slug}`}>View More -&gt;</Link></div>)}</div></div>; }
